[package]
authors = ["Kent Gibson <warthog618@gmail.com>"]
categories = ["hardware-support", "os::linux-apis", "embedded", "external-ffi-bindings"]
description = "A low level library to access GPIO lines on Linux using the GPIO character device"
edition = "2021"
keywords = ["linux", "gpio", "library", "embedded"]
license = "MIT"
name = "gpiocdev-uapi"
version = "0.1.0"

[dependencies]
bitflags = "1.3"
bitmaps = {version = "3.1.0"}
libc = "0.2"
nix = "0.24.1"
thiserror = "1.0"

[features]
default = ["uapi_v2"]
uapi_v1 = []
uapi_v2 = []
