[package]
authors = ["Kent Gibson <warthog618@gmail.com>"]
categories = ["hardware-support", "command-line-utilities", "embedded", "os::linux-apis"]
description = "A tool to access GPIO lines on Linux using the GPIO character device"
edition = "2021"
keywords = ["linux", "gpio", "cli", "embedded"]
license = "MIT"
name = "gpiocdev-cli"
version = "0.1.0"

[[bin]]
name="gpiocdev"
path="src/main.rs"

[dependencies]
anyhow = "1.0"
clap = {version = "4.0", features = ["derive", "env"]}
colored = "2"
daemonize = "0.4.1"
gpiocdev = {path = "../lib", features = ["uapi_v1", "uapi_v2"]}
rustyline = "10.0"
rustyline-derive = "0.7"
thiserror = "1.0"
